[package]
name = "pyhocon-rs-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pyhocon_rs_core"
crate-type = ["cdylib"]

[dependencies]
hocon = "0.9.0"
pyo3 = "0.25.0"
